version: '3.1'

services: 
  
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DATABASE: admin
      POSTGRES_USER: admin
      POSTGRES_ROOT_PASSWORD: admin
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d